### ISSUE TITLE
`prefab.system.ssh.authorize()` returns `False` while it succeeded, why?

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/core9#131]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu 16.04

#### Detailed description

`prefab.system.ssh.authorize()` returns `False` while it succeeded, why?

<img width="803" alt="screen shot 2017-12-07 at 11 10 42" src="https://user-images.githubusercontent.com/13795109/33710570-4af07c7e-db41-11e7-9b39-1100ca71d22a.png">

#### Steps to reproduce

```python
# vars
ovc_url = "se-gen-1.demo.greenitglobe.com"
location = "se-gen-1"
account_name = "Account_of_Yves"
cloud_space_name = "test-space"
host_name = "ays-server"
import os
app_id = os.environ["APP_ID"]
secret = os.environ["SECRET"]
key_path = os.path.expanduser("~/.ssh/mykey")

# create machine
ovc_client = j.clients.openvcloud.get(app_id, secret, ovc_url)
account = ovc_client.account_get(account_name, create=False) 
vdc = account.space_get(cloud_space_name, location)
j.clients.ssh.load_ssh_key(path=key_path, create_keys=True)
host = vdc.machine_create(host_name, "mykey", sizeId=3)

# fetch "default" key from ItsYou.online profile
iyo_user = j.clients.itsyouonline.get_user(app_id, secret)
pubkey = iyo_user.public_keys.get("default")

# authorize this key
prefab.system.ssh.authorize("root", pubkey.model["publickey"])
```

**Comment by ahussein** [comment]
The code just returns false if the key is not already in the knownhosts file of the target node. I do not see a good reason why this return value is set. But we will need to check all other code that uses this API before changing its behavior.
