### ISSUE TITLE
WIP: minor client issues

### ISSUE THREAD

**Issue by serboctor** [Jumpscale/core9#138]
#### Installation information

- jumpscale version: master
- operating system: ubuntu

#### Detailed description
This issue is still a WIP, I am adding issues as I find them. Please don't pick it up until WIP is removed from the title.

Issues in git client:
- Function argument `branch` in `getGitRepoArgs` is not used in the function despite otherwise stated in the docstring.
- Function argument `errorIfNone` in `getGitReposListLocal` is not used in the function and an error is raised even if it is set to false.
- `getContentInfoFromUrl`  clones the repo if it doesn't exist locally  which makes the name of the function very misleading and the docstrings dont mention the cloning part. Also, all the data returned by this function are returned by calling self.parseURL.

**Comment by andrewayoub** [comment]
solved in these commits 
dfc9c7615a2d4d2c791dab7890be15ca12037ee2
5c8258174e3d499ded2478f72cb152d38a276f1b
dfc9c7615a2d4d2c791dab7890be15ca12037ee2
