### ISSUE TITLE
"j.sal.process.execute" doesn't work properly

### ISSUE THREAD

**Issue by alichaddad** [Jumpscale/core9#147]
#### Installation information

- jumpscale version:9.3.0
- operating system:Ubuntu

#### Detailed description
The returned output is incomplete when executing commands that may have long stream as an output.

#### Steps to reproduce
An example command:
```
cmd = 'nmap -n --disable-arp-ping -send-ip -Pn -sS -p{port} -oX - {cidr}'
code, output, err = j.sal.process.execute(cmd, showout=False, die=False) 
```

**Comment by ahussein** [comment]
This also cause ays not to be able to list template repos since the command used to search ays template repos also is also affected by this bug.
