### ISSUE TITLE
Interfaces from j.sal.nic.nics different than interfaces from ifconfig

### ISSUE THREAD

**Issue by Dinaamagdy** [Jumpscale/core9#169]
## Issue:
use j.sal.nic.nics  to get network interfaces, and compare the result with ifconfig , i found one difference ```bonding_masters```, and when I tried to get its ip with j.sal.nic.ipGet raises the following error : 

```
   nic_ip_mask = j.sal.nic.ipGet(device)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/sal/nic/UnixNetworkManager.py", line 34, in ipGet
    ipmask = netaddr.IPNetwork(res)
  File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 938, in __init__
    raise AddrFormatError('invalid IPNetwork %s' % addr)
netaddr.core.AddrFormatError: invalid IPNetwork 00:00:00:00:00:00

```
## Software version : 
tried it on packet machine
on dev branch

**Comment by hossamabdullah** [comment]
will remove this component, use j.sal.nettools instead
