### ISSUE TITLE
AYS9 repo create still uses /optvar instead of /opt/var/

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/core9#19]
#### Installation information

- jumpscale version: db9386706021ed653eb6498d0044f2e66500ec68 (master)
- operating system: Linux

#### Detailed description

AYS9 repo create still uses /optvar instead of /opt/var/

All of js9 now uses /opt/var please be consistant for ays repos aswell

**Comment by alichaddad** [comment]
repo will be created in configured `VARDIR`
https://github.com/Jumpscale/ays9/commit/2ef8d0ad834e35505d91e1a79e67eff9e8cda10f
