### ISSUE TITLE
broken 9.3.0 installation on container

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/core9#199]
#### Installation information

- jumpscale version: 9.3.0
- operating system: all

#### Detailed description

Config path gets set to {HOME}/js9host/cfg, which CANNOT work, because config will point to non-existing, non-mounted dirs.

![photo_2018-02-25_18-07-03](https://user-images.githubusercontent.com/8425762/36643638-2a79f0ba-1a57-11e8-9703-44185f9c1bb8.jpg)

**Comment by arahmanhamdy** [comment]
I tested it on mac and it works well.
