### ISSUE TITLE
migrate extratools

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/core9#2]
https://github.com/Jumpscale/core9/blob/master/install/ExtraTools.py

- check which methods are useful and move them to right js lib
- document them well

make sure is on branch, so we can check

**Comment by ashraffouda** [comment]
https://github.com/Jumpscale/core9/pull/38
https://github.com/Jumpscale/lib9/pull/19

**Comment by john-kheir** [comment]
ImportError: No module named 'blosc'

**Comment by rkhamis** [comment]
@john-kheir should be fixed by https://github.com/Jumpscale/lib9/pull/20

**Comment by ashraffouda** [comment]
fixed
