### ISSUE TITLE
j.clients.sshkey.key_generate(path="...", passphrase='hello') asks for passphrase

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/core9#213]
#### Installation information

- jumpscale version: development
- operating system: Ubuntu 16.04 on be-gen-1

#### Detailed description

Executing the below code to create a new SSH key, asks to specify a passphrase, even when passing the passphrase as an argument.

#### Steps to reproduce

```python
import os
ssh_key_name = "id_rsa"
ssh_key_path = os.path.expanduser("~/.ssh/{}".format(ssh_key_name))
j.clients.sshkey.key_generate(path=ssh_key_path, passphrase='hello', overwrite=False, load=False, returnObj=True)
```

**Comment by rkhamis** [comment]
no longer the case
