### ISSUE TITLE
j.clients.sshkey.key_generate() finds key in agent, while no agent is running

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/core9#214]
#### Installation information

- jumpscale version: development
- operating system: Ubuntu 16.04

#### Detailed description

Creating a new SSH key using the code below, results in the message `JS9 init: ssh key found in agent is:'/root/.ssh/id_rsa`, while there is no ssh-agent running, so how can it be loaded?

#### Steps to reproduce

```python
import os
ssh_key_name = "id_rsa"
ssh_key_path = os.path.expanduser("~/.ssh/{}".format(ssh_key_name))
j.clients.sshkey.key_generate(path=ssh_key_path, passphrase='hello', overwrite=False, load=False, returnObj=True)
```

Result:
```python
In [2]: j.clients.sshkey.key_generate(path=ssh_key_path, passphrase='hello', overwrite=False, load=False, returnObj=True)
* JS9 init: ssh key found in agent is:'/root/.ssh/id_rsa'
* JS9 init: Is it ok to use this one:'/root/.ssh/id_rsa'?
 [y/n]:
```

**Comment by rkhamis** [comment]
here it's checking for the key configured in your myconfig, which is used to encrypt the config data of the generated key (also happens to be the same one)

@yveskerwyn please close if you have no further questions there
