### ISSUE TITLE
loading js9 needs to work without using linux commands

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/core9#216]
![image](https://user-images.githubusercontent.com/6021844/37566974-e3e84642-2ac8-11e8-8ab8-64170bf599c0.png)

**Comment by arahmanhamdy** [comment]
`uname` command isn't called from js9, could you check if your `.bash_profile` or `.bashrc` files are sourcing bash tools which calls `uname ` implictly?

**Comment by despiegk** [comment]
resolved
