### ISSUE TITLE
js9_config init => twice the question about which key to use

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/core9#220]
FIRST CHECK ISSUE: #218 

#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu VM

#### Detailed description

After resetting with `js9_reset`, `js9_config init` resulted in question about which key to use, then the interactive screen for main, so far OK, but then again the question about key which key to use.

#### Steps to reproduce

See `ssh root@185.15.201.111 -p7922`

**Comment by ahussein** [comment]
This happens whey you manually set the path attribute of the myconfig section to "" then the configmanager is trying to figure out the path of the configurations while configuring the sshkey itself.
If your path attribute is correctly set which will happen automatically then you will not see that problem.
