### ISSUE TITLE
js9_config init lists two keys to choose from, one of them doesn't exist any more

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/core9#221]
FIRST CHECK ISSUE: #218 

- jumpscale version: 9.3.0
- operating system: Ubuntu VM

#### Detailed description

`js9_config init` lists two ssh keys, one doesn't exist anymore, so not sure why it is still listed

#### Steps to reproduce

See `ssh root@185.15.201.111 -p7922`

**Comment by ahussein** [comment]
I cannot reproduce this.
