### ISSUE TITLE
js9_config reset should start ssh-agent if not started yet and ask which key to load from .ssh dir

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/core9#222]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu VM

#### Detailed description

Currently if you execute `js9_config reset` it is required that ssh-agent is already running.

Change request:
-> if no ssh-agent is running yet
     - it should start ssh-agent
     - list all keys in `~/.ssh` and ask to choose from
     - load the chosen key

-> if ssh-agent is already running:
     - list all keys in `~/.ssh` and ask to choose from
     - load the chosen key

**Comment by yveskerwyn** [comment]
Of course in case there is `./keys` directory in the current directory it should load the SSH key in that directory, and delete the configuration instances in `./secureconfig`

**Comment by yveskerwyn** [comment]
Extra feedback, when executing  `js9_config init`:
```bash
* found 0 keys from ssh-agent
* JS9 init: ssh key found in agent is:'/root/.ssh/id_rsa'
* JS9 init: Is it ok to use this one:'/root/.ssh/id_rsa'?
 [y/n]: y
* JS9 init: Do you want to use a git based CONFIG dir, y/n?
 [y/n]: n
* JS9 init: will create config dir in '/opt/cfg/myconfig/', your config will not be centralised! Is this ok?
 [y/n]: y
* JS9 init: ssh key found in agent is:'/root/.ssh/id_rsa'
* JS9 init: Is it ok to use this one:'/root/.ssh/id_rsa'?
 [y/n]:
```

1. On the second line JumpScale says: "ssh key found in agent is:'/root/.ssh/id_rsa'"
  --> this is an error since no key was loaded, as confirmed in the first line
  --> the message should be "ssh key found in `/root/.ssh/` is:'id_rsa'"

2. After successful initialization it turns out that no SSH key is loaded:

```
ssh-add -l
Could not open a connection to your authentication agent.
```

Is this normal?

**Comment by yveskerwyn** [comment]
Answer I got from @ahussein on my second question:
if you didnt export the `SSH_AUTH_SOCK` variable then the JumpScale will create a socket file under /tmp/sshagent_socket. if you `export SSH_AUTH_SOCK=/tmp/sshagent_socket` and then try to do `ssh-add -l` then it will work:
```bash
export SSH_AUTH_SOCK=/tmp/sshagent_socket
ssh-add -l
```

**Comment by despiegk** [comment]
thats manual should not be needed, when using js9 to start all is done
we don't want anything manual
