### ISSUE TITLE
getting prefab client does not work from development 

### ISSUE THREAD

**Issue by abdulrahmantkhalifa** [Jumpscale/core9#228]
#### Installation information

- jumpscale version: development branch 
  - core9 - commit 8936c330a6322a3a411f61d38a327cff2a12facc
  - prefab9  - commit 463c44eb1064234a83fc5f2361a3c00932b16442
  - lib9 - commit ba89e2c88944122eaad448ec6551a19a71e2fff7
- operating system: ubuntu 1604

#### Detailed description
after installing jumpscale , when trying to get a prefab through j.tools.prefab.get(executor)
gives a segmentation fault error with no traceback

#### Steps to reproduce
work around is installing a dirty repo from version 1.4 through , this is by no means a permenant solution
```
pip3 install http://home.maxux.net/wheelhouse/ssh2_python-0.10.0%2B4.g7dc3833.dirty-cp35-cp35m-manylinux1_x86_64.whl 
pip3 install parallel_ssh>=1.4.0, 
```

**Comment by alichaddad** [comment]
This is fixed already
