### ISSUE TITLE
js9_config init doesn't pass the --key value to the interactive screen

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/core9#231]
#### Installation information

- jumpscale version: developement
- operating system: Ubuntu 16.04

#### Detailed description

When initializing the Config Manager on a fresh JS environment, using the steps below, you get to see an "empty" configuration screen for the SSH key, most notably the `path` field is not filled out with the value passed through the `--key` option when using  `js9_config init`:

![screen shot 2018-05-04 at 09 27 27](https://user-images.githubusercontent.com/13795109/39616882-d0bbbffc-4f7d-11e8-9612-4dba2326b62d.png)
 

#### Steps to reproduce

```bash
# Create a SSH key pair for encrypting the secret data
JS_CONFIG_SSHKEY_PATH="/root/.ssh/jsconfig_key"
ssh-keygen -t rsa -f $JS_CONFIG_SSHKEY_PATH -P ''

# Create a directory in j.dirs.CODEDIR for storing the config instances
GIT_SERVER="docs.grid.tf"
GIT_ACCOUNT="yves"
REPO_NAME="my_jsconfig"
JS_CONFIG_REPO_DIR="/opt/code/$GIT_SERVER/$GIT_ACCOUNT/$REPO_NAME"
mkdir -p $JS_CONFIG_REPO_DIR

# Optionally make this directory a Git repository
cd $JS_CONFIG_REPO_DIR
git init 

# Mark this directory as your config repository
js9_config init --path $JS_CONFIG_REPO_DIR --key $JS_CONFIG_SSHKEY_PATH
```

**Comment by alichaddad** [comment]
See https://github.com/Jumpscale/core9/commit/3bd57898d7967cbbfc193f6da6bba909554b3558
