### ISSUE TITLE
Git client getBranchOrTag method always return tag even is repo is on a branc

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/core9#50]
#### Installation information

- jumpscale version: master
- operating system: linux

#### Steps to reproduce
in a repo where it exists tag, but you are currently on a branch do:
```python
git = j.clients.git.get('/opt/code/github/jumpscale/ays9')
git.getBranchOrTag()
```
It will return the more recent tag available, which is wrong. It should return the branch name.

I checked the code of this function, it use git describe, so if any tag exists on the repo, it will never return the branch name. this is wrong.

**Comment by rkhamis** [comment]
Version should be from JumpScale9 package.

**Comment by zaibon** [comment]
` git symbolic-ref -q --short HEAD || git describe --tags --exact-match`
should do the trick

**Comment by ashraffouda** [comment]
https://github.com/Jumpscale/core9/pull/109
