### ISSUE TITLE
useless log message when interpreter starts

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/core9#59]
Every time you start the js9 interpreter you got this log message `[Mon21 13:06] - SystemProcess.py    :661 :j.sal.process                  - INFO     - Checking whether at least 1 processes redis-server are running
`

This is useless and polute the ouput of some commands.

**Comment by rkhamis** [comment]
We can set it to debug

**Comment by zaibon** [comment]
But even then, what's the value of this message ?

**Comment by rkhamis** [comment]
logging is not bad practice. I see no reason to remove logs, but appropriate levels should be met.
