### ISSUE TITLE
Installation verification

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/core9#79]
#### Installation information

- jumpscale version: 9.3.0
- operating system: all

#### Detailed description
Make sure that install works on a clean system.
   - config files are written in expected locations
   - no missing config
   - js9_config works
   - js9_code works
   - verify dirs on executor base and prefab and filesystem to be consistent

**Comment by abdulrahmantkhalifa** [comment]
https://github.com/Jumpscale/prefab9/commit/407047d6847250cc207e4ffbec1247d0f01aaf64
