### ISSUE TITLE
j.clients.ssh.ssh_agent_check() doesn't do anything

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/core9#87]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu

What is it for?
Please a docstring

#### Detailed description

![screen shot 2017-11-06 at 17 14 39](https://user-images.githubusercontent.com/13795109/32450997-0af696be-c316-11e7-941a-eb097706a49b.png)

**Comment by despiegk** [comment]
it checks there is an ssh_agent running, nothing more nothing less

**Comment by rkhamis** [comment]
@alichaddad please add docstring and return something helpful
